"""add password_hash to profiles

Revision ID: 03d0e6cde4f7
Revises: d0def9feeedd
Create Date: 2026-07-21 21:13:39.503738
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "03d0e6cde4f7"
down_revision: str | None = "d0def9feeedd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profiles", sa.Column("password_hash", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "password_hash")
    # ### end Alembic commands ###
