"""initial schema

Revision ID: 2e93fabef7dd
Revises:
Create Date: 2026-07-02 11:47:59.856302
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "2e93fabef7dd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("segment", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "segment IS NULL OR segment IN ('retail', 'wholesale', 'online')",
            name=op.f("ck_customers_valid_segment"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_table(
        "data_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_domain", sa.String(), nullable=False),
        sa.Column("schedule_cron", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('csv_upload', 'excel_upload', 'rest_api', 'postgres')",
            name=op.f("ck_data_sources_valid_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'error')", name=op.f("ck_data_sources_valid_status")
        ),
        sa.CheckConstraint(
            "target_domain IN ('sales', 'finance', 'inventory')",
            name=op.f("ck_data_sources_valid_domain"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
        sa.UniqueConstraint("name", name=op.f("uq_data_sources_name")),
    )
    op.create_table(
        "kpi_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("metric", sa.String(), nullable=False),
        sa.Column("dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kpi_snapshots")),
        sa.UniqueConstraint("snapshot_date", "metric", "dimensions", name="uq_kpi_point"),
    )
    op.create_index(
        "ix_kpi_snapshots_date_metric", "kpi_snapshots", ["snapshot_date", "metric"], unique=False
    )
    op.create_table(
        "ml_models",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("model_type", sa.String(), nullable=False),
        sa.Column("target", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("trained_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("training_rows", sa.Integer(), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("artifact_s3_key", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "model_type IN ('prophet', 'arima', 'isolation_forest', 'regression_ensemble')",
            name=op.f("ck_ml_models_valid_model_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ml_models")),
        sa.UniqueConstraint("model_type", "target", "version", name="uq_model_version"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("sku", name=op.f("uq_products_sku")),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("department", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "role IN ('admin', 'manager', 'analyst')", name=op.f("ck_profiles_valid_role")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles")),
        sa.UniqueConstraint("email", name=op.f("uq_profiles_email")),
    )
    op.create_table(
        "alert_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("metric", sa.String(), nullable=False),
        sa.Column("condition", sa.String(), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("channels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("roles_notified", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "condition IN ('gt', 'lt', 'pct_change_gt', 'anomaly_detected')",
            name=op.f("ck_alert_rules_valid_condition"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["profiles.id"],
            name=op.f("fk_alert_rules_created_by_profiles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_rules")),
    )
    op.create_table(
        "anomalies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("detected_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("metric", sa.String(), nullable=False),
        sa.Column("observed_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("expected_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("deviation_score", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("acknowledged_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high')", name=op.f("ck_anomalies_valid_severity")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'acknowledged', 'dismissed')",
            name=op.f("ck_anomalies_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"],
            ["profiles.id"],
            name=op.f("fk_anomalies_acknowledged_by_profiles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anomalies")),
    )
    op.create_index("ix_anomalies_status", "anomalies", ["status"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("entity", sa.String(), nullable=True),
        sa.Column("entity_id", sa.String(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["profiles.id"],
            name=op.f("fk_audit_logs_user_id_profiles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"], unique=False)
    op.create_table(
        "etl_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("data_source_id", sa.UUID(), nullable=True),
        sa.Column("trigger", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("rows_in", sa.Integer(), nullable=True),
        sa.Column("rows_loaded", sa.Integer(), nullable=True),
        sa.Column("rows_rejected", sa.Integer(), nullable=True),
        sa.Column("log", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')", name=op.f("ck_etl_jobs_valid_status")
        ),
        sa.CheckConstraint(
            "trigger IN ('manual', 'schedule', 'upload')", name=op.f("ck_etl_jobs_valid_trigger")
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_etl_jobs_data_source_id_data_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_etl_jobs")),
    )
    op.create_table(
        "forecasts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("target", sa.String(), nullable=False),
        sa.Column("forecast_date", sa.Date(), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("yhat", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("yhat_lower", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("yhat_upper", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("generated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["ml_models.id"],
            name=op.f("fk_forecasts_model_id_ml_models"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecasts")),
        sa.UniqueConstraint("model_id", "target", "forecast_date", name="uq_forecast_point"),
    )
    op.create_index(
        "ix_forecasts_target_date", "forecasts", ["target", "forecast_date"], unique=False
    )
    op.create_table(
        "inventory_levels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("quantity_on_hand", sa.Integer(), nullable=False),
        sa.Column("reorder_level", sa.Integer(), nullable=False),
        sa.Column("warehouse", sa.String(), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_levels_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_inventory_levels_source_id_data_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_levels")),
        sa.UniqueConstraint(
            "snapshot_date", "product_id", "warehouse", name="uq_inventory_snapshot"
        ),
    )
    op.create_index(
        "ix_inventory_snapshot_date", "inventory_levels", ["snapshot_date"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_type", sa.String(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=True),
        sa.Column("generated_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("format IN ('pdf', 'xlsx')", name=op.f("ck_reports_valid_format")),
        sa.CheckConstraint(
            "report_type IN ('weekly_summary', 'monthly_summary', 'custom')",
            name=op.f("ck_reports_valid_report_type"),
        ),
        sa.ForeignKeyConstraint(
            ["generated_by"],
            ["profiles.id"],
            name=op.f("fk_reports_generated_by_profiles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_table(
        "raw_uploads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("data_source_id", sa.UUID(), nullable=True),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=True),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('received', 'validated', 'loaded', 'failed')",
            name=op.f("ck_raw_uploads_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_raw_uploads_data_source_id_data_sources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["profiles.id"],
            name=op.f("fk_raw_uploads_uploaded_by_profiles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_uploads")),
        schema="staging",
    )
    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("department", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("row_hash", sa.String(), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("etl_job_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "category IN ('rent', 'salaries', 'utilities', 'marketing', 'logistics', 'other')",
            name=op.f("ck_expenses_valid_category"),
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_expenses_non_negative_amount")),
        sa.ForeignKeyConstraint(
            ["etl_job_id"],
            ["etl_jobs.id"],
            name=op.f("fk_expenses_etl_job_id_etl_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_expenses_source_id_data_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
        sa.UniqueConstraint("row_hash", name=op.f("uq_expenses_row_hash")),
    )
    op.create_index("ix_expenses_expense_date", "expenses", ["expense_date"], unique=False)
    op.create_table(
        "insights",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("insight_type", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("related_anomaly_id", sa.UUID(), nullable=True),
        sa.Column("related_forecast_id", sa.Integer(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("generated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("dedupe_key", sa.String(), nullable=True),
        sa.CheckConstraint(
            "insight_type IN ('trend', 'forecast', 'anomaly', 'comparison', 'recommendation')",
            name=op.f("ck_insights_valid_type"),
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'critical')", name=op.f("ck_insights_valid_severity")
        ),
        sa.ForeignKeyConstraint(
            ["related_anomaly_id"],
            ["anomalies.id"],
            name=op.f("fk_insights_related_anomaly_id_anomalies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["related_forecast_id"],
            ["forecasts.id"],
            name=op.f("fk_insights_related_forecast_id_forecasts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insights")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_insights_dedupe_key")),
    )
    op.create_index("ix_insights_generated_at", "insights", ["generated_at"], unique=False)
    op.create_table(
        "sales_transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("txn_date", sa.Date(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("channel", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("row_hash", sa.String(), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("etl_job_id", sa.UUID(), nullable=True),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_sales_transactions_positive_quantity")),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_sales_transactions_customer_id_customers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["etl_job_id"],
            ["etl_jobs.id"],
            name=op.f("fk_sales_transactions_etl_job_id_etl_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_sales_transactions_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_sales_transactions_source_id_data_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_transactions")),
        sa.UniqueConstraint("row_hash", name=op.f("uq_sales_transactions_row_hash")),
    )
    op.create_index("ix_sales_txn_date", "sales_transactions", ["txn_date"], unique=False)
    op.create_index(
        "ix_sales_txn_date_product", "sales_transactions", ["txn_date", "product_id"], unique=False
    )
    op.create_index(
        "ix_sales_txn_date_region", "sales_transactions", ["txn_date", "region"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("alert_rule_id", sa.UUID(), nullable=True),
        sa.Column("insight_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_rule_id"],
            ["alert_rules.id"],
            name=op.f("fk_notifications_alert_rule_id_alert_rules"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["insight_id"],
            ["insights.id"],
            name=op.f("fk_notifications_insight_id_insights"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["profiles.id"],
            name=op.f("fk_notifications_user_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_user_unread", "notifications", ["user_id", "is_read"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notifications_user_unread", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_sales_txn_date_region", table_name="sales_transactions")
    op.drop_index("ix_sales_txn_date_product", table_name="sales_transactions")
    op.drop_index("ix_sales_txn_date", table_name="sales_transactions")
    op.drop_table("sales_transactions")
    op.drop_index("ix_insights_generated_at", table_name="insights")
    op.drop_table("insights")
    op.drop_index("ix_expenses_expense_date", table_name="expenses")
    op.drop_table("expenses")
    op.drop_table("raw_uploads", schema="staging")
    op.drop_table("reports")
    op.drop_index("ix_inventory_snapshot_date", table_name="inventory_levels")
    op.drop_table("inventory_levels")
    op.drop_index("ix_forecasts_target_date", table_name="forecasts")
    op.drop_table("forecasts")
    op.drop_table("etl_jobs")
    op.drop_index("ix_audit_logs_created_at", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_anomalies_status", table_name="anomalies")
    op.drop_table("anomalies")
    op.drop_table("alert_rules")
    op.drop_table("profiles")
    op.drop_table("products")
    op.drop_table("ml_models")
    op.drop_index("ix_kpi_snapshots_date_metric", table_name="kpi_snapshots")
    op.drop_table("kpi_snapshots")
    op.drop_table("data_sources")
    op.drop_table("customers")
    # ### end Alembic commands ###
