"""add report schedules

Revision ID: 511e98ca2e4e
Revises: f2a7c9d41b30
Create Date: 2026-08-19 08:54:55.375259
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '511e98ca2e4e'
down_revision: str | None = 'f2a7c9d41b30'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.Date(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_report_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("format IN ('pdf', 'xlsx')", name=op.f('ck_report_schedules_valid_schedule_format')),
    sa.CheckConstraint("frequency IN ('weekly', 'monthly')", name=op.f('ck_report_schedules_valid_frequency')),
    sa.CheckConstraint('day_of_month IS NULL OR (day_of_month BETWEEN 1 AND 28)', name=op.f('ck_report_schedules_valid_day_of_month')),
    sa.CheckConstraint('day_of_week IS NULL OR (day_of_week BETWEEN 0 AND 6)', name=op.f('ck_report_schedules_valid_day_of_week')),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], name=op.f('fk_report_schedules_created_by_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_report_id'], ['reports.id'], name=op.f('fk_report_schedules_last_report_id_reports'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_schedules'))
    )
    op.create_index('ix_report_schedules_due', 'report_schedules', ['is_active', 'next_run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_report_schedules_due', table_name='report_schedules')
    op.drop_table('report_schedules')
    # ### end Alembic commands ###
