"""add preferences to profiles

Revision ID: 75d6a4fce3bd
Revises: ec27b24c6c94
Create Date: 2026-07-21 21:43:44.256491
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '75d6a4fce3bd'
down_revision: str | None = 'ec27b24c6c94'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'preferences')
    # ### end Alembic commands ###
